export function inviteEmail(opts: { brand: string; tenantSlug: string; tempPassword?: string | null; loginUrl: string }) {
  const { brand, tenantSlug, tempPassword, loginUrl } = opts;
  const subject = `You have been invited to ${brand}`;
  const lines = [
    `You have been invited to join "${brand}" (${tenantSlug}).`,
    ``,
    `Login: ${loginUrl}`,
  ];
  if (tempPassword) {
    lines.push(`Temporary password: ${tempPassword}`, ``, `Please change it after logging in.`);
  }
  const text = lines.join("\n");
  const html = `
    <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;line-height:1.5">
      <h2>You have been invited to ${brand}</h2>
      <p>You have been invited to join <b>${brand}</b> (<code>${tenantSlug}</code>).</p>
      <p><a href="${loginUrl}">Open login</a></p>
      ${tempPassword ? `<p><b>Temporary password:</b> <code>${tempPassword}</code><br/>Please change it after logging in.</p>` : ``}
      <hr/>
      <p style="color:#666;font-size:12px">Generated by WebCompliance Platform</p>
    </div>
  `.trim();
  return { subject, text, html };
}
