export function monitorAlertEmail(opts: { brand: string; tenantSlug: string; checkName: string; status: string; message: string; url: string }) {
  const { brand, tenantSlug, checkName, status, message, url } = opts;
  const subject = `[${tenantSlug}] Monitor alert: ${checkName} is ${status}`;
  const text = [
    `${brand} – Monitor alert`,
    `Tenant: ${tenantSlug}`,
    `Check: ${checkName}`,
    `Status: ${status}`,
    ``,
    message,
    ``,
    `Open monitor: ${url}`,
  ].join("\n");
  const html = `
    <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;line-height:1.5">
      <h2>Monitor alert</h2>
      <p><b>${checkName}</b> is <b>${status}</b>.</p>
      <p style="white-space:pre-wrap">${message}</p>
      <p><a href="${url}">Open monitor</a></p>
      <hr/>
      <p style="color:#666;font-size:12px">Generated by WebCompliance Platform</p>
    </div>
  `.trim();
  return { subject, text, html };
}
