export function ticketNotificationEmail(opts: { brand: string; tenantSlug: string; ticketId: string; title: string; message: string; url: string }) {
  const { brand, tenantSlug, ticketId, title, message, url } = opts;
  const subject = `[${tenantSlug}] Ticket update: ${title}`;
  const text = [
    `${brand} – Ticket update`,
    `Tenant: ${tenantSlug}`,
    `Ticket: ${ticketId}`,
    ``,
    message,
    ``,
    `Open: ${url}`,
  ].join("\n");
  const html = `
    <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;line-height:1.5">
      <h2>Ticket update</h2>
      <p><b>${title}</b></p>
      <p style="white-space:pre-wrap">${message}</p>
      <p><a href="${url}">Open ticket</a></p>
      <hr/>
      <p style="color:#666;font-size:12px">Generated by WebCompliance Platform</p>
    </div>
  `.trim();
  return { subject, text, html };
}
