import React from "react";

export default function LegalShell({
  title,
  lastUpdated,
  children,
}: {
  title: string;
  lastUpdated?: string | null;
  children: React.ReactNode;
}) {
  return (
    <main className="prose max-w-none">
      <h1>{title}</h1>

      {lastUpdated ? (
        <p className="text-sm text-muted-foreground">
          Última actualización: <strong>{lastUpdated}</strong>
        </p>
      ) : null}

      <div className="not-prose my-4 rounded border bg-amber-50 p-4 text-sm">
        <div className="font-medium">Nota</div>
        <p className="mt-1 text-muted-foreground">
          Este documento es una base editable. Para un cumplimiento perfecto según tu actividad y jurisdicción,
          recomendamos revisión por asesoría legal.
        </p>
      </div>

      {children}

      <hr />
      <p className="text-xs text-muted-foreground not-prose">
        Generated by <span className="font-medium">WebCompliance Platform</span>.
      </p>
    </main>
  );
}
