import Link from "next/link";
import { requireTenantContextPage } from "@/lib/tenant-auth";
import { AppCard } from "@/components/app-ui/AppCard";

export default async function EvidenceOperationsPage({
  params,
}: {
  params: Promise<{ tenant: string }>;
}) {
  const { tenant } = await params;
  const ctx = await requireTenantContextPage(tenant);

  return (
    <main className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold">Operations evidence</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Monitoring, uptime and incident workflow — the operational proof trail.
          </p>
        </div>

        <Link
          href={`/app/${tenant}/evidence/bundles`}
          className="inline-flex items-center rounded-xl border bg-bg2/60 px-4 py-2 text-sm transition hover:bg-bg2/80"
        >
          Export evidence →
        </Link>
      </div>

      <div className="grid gap-3 md:grid-cols-3">
        <Link href={`/app/${tenant}/monitor`} className="block">
          <AppCard className="p-4 transition hover:-translate-y-[1px] hover:shadow-sm">
            <div className="text-xs text-muted-foreground">Monitoring</div>
            <div className="mt-1 text-lg font-semibold">Uptime + SSL checks</div>
            <div className="mt-1 text-sm text-muted-foreground">
              {ctx.features.monitoring
                ? "Checks and events generated by your cron runner."
                : "Not enabled on your plan."}
            </div>
          </AppCard>
        </Link>

        <Link href={`/app/${tenant}/incidents`} className="block">
          <AppCard className="p-4 transition hover:-translate-y-[1px] hover:shadow-sm">
            <div className="text-xs text-muted-foreground">Incidents</div>
            <div className="mt-1 text-lg font-semibold">Response workflow</div>
            <div className="mt-1 text-sm text-muted-foreground">
              Track incidents and actions taken (proof of diligence).
            </div>
          </AppCard>
        </Link>

        <Link href={`/app/${tenant}/tickets`} className="block">
          <AppCard className="p-4 transition hover:-translate-y-[1px] hover:shadow-sm">
            <div className="text-xs text-muted-foreground">Tickets</div>
            <div className="mt-1 text-lg font-semibold">Requests + tasks</div>
            <div className="mt-1 text-sm text-muted-foreground">
              Audit-friendly record of work done and decisions.
            </div>
          </AppCard>
        </Link>
      </div>

      <AppCard className="p-4">
        <div className="text-sm font-semibold">Founder signal</div>
        <div className="mt-1 text-sm text-muted-foreground">
          If monitoring events stop flowing, you lose operational evidence. Keep checks enabled and incident tickets
          documented.
        </div>
      </AppCard>
    </main>
  );
}
